spring.config.import=optional:file:src/main/resources/application-secret.properties
spring.application.name=bank-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# создаст таблицы по нашим Java-классам
spring.jpa.hibernate.ddl-auto=update

# показывать SQL-запросы в консоли
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# чтобы Hibernate понимал диалект именно Postgres 17
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect